language: node_js
node_js: node
services:
- mongodb
env:
- NODE_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: OLpQUJpTVGHxwXe6vgKcb8am2DED3vHnUarIdiHyQJAYdfiBD7pxZsJi6/hwvsXyXr6HPvkATxHCA5/pNwggEDz0MPQLGTbRv4+//GYm5Jy954hwVZTEDevb+QGwXu9CGIcyOHuS9u7zqq4Jig2yq95Be54EciNVn8/FEJXzAfSIpHEDnkAn0HHGutDfi8zdV7YzE/j5tFs/dzylqQYc0nLfkh+FJEHZkpgdDV5r9MBEXl19OnrkgUku7Rewfsr6GOBxDbsGgqeY8uOQM26qPzbJEms+xg9wT1jQB9CM0ToQN6z893YuWphzsfB7EhrMG5p/zXxLsP4GUsYatu12t7tY4CnQbniqHvO+e9SIqnnPS0mRslpwDxIgfkQ+MvGm6wvWnB5jYJXo0YAl8GK7m3JepPKx/IczMRcI+nVLfkFJVkHMU3/aASXRJF8nMnQ6tsH1YkZVJooBjj9mQpQW8AHevInbXNGsuR5wpvuykx3XYpeLewLOLOs3LpdTuZWQjo+bvlmNy1oyt/3dJSdlfvMPpl22+etyspHXPgNb6kiKu67rh8aM8l5eL4NSAkprC7yWOMkfBhegpq53MKmSSxT1gbdQ4SRxfXMX45zt1SfrlA2kvdOp3L/D4C2syD5mz4qmOWVtdCdwsgvyGl5oJnwIEkq8/UwsMGGnAEp6hKs=
  app: jeff-noteful-v3
  on:
    repo: thinkful-ei19/jeff-noteful-v3
